// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/libssh/ssh.go
//
// Generated by this command:
//
//	mockgen -source=pkg/libssh/ssh.go -destination=utils/mock/mock_ssh.go -package=kubevirtcimocks
//

// Package kubevirtcimocks is a generated GoMock package.
package kubevirtcimocks

import (
	fs "io/fs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockClient) Command(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Command indicates an expected call of Command.
func (mr *MockClientMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockClient)(nil).Command), cmd)
}

// CommandWithNoStdOut mocks base method.
func (m *MockClient) CommandWithNoStdOut(cmd string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandWithNoStdOut", cmd)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommandWithNoStdOut indicates an expected call of CommandWithNoStdOut.
func (mr *MockClientMockRecorder) CommandWithNoStdOut(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandWithNoStdOut", reflect.TypeOf((*MockClient)(nil).CommandWithNoStdOut), cmd)
}

// CopyRemoteFile mocks base method.
func (m *MockClient) CopyRemoteFile(remotePath, localPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyRemoteFile", remotePath, localPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyRemoteFile indicates an expected call of CopyRemoteFile.
func (mr *MockClientMockRecorder) CopyRemoteFile(remotePath, localPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyRemoteFile", reflect.TypeOf((*MockClient)(nil).CopyRemoteFile), remotePath, localPath)
}

// SCP mocks base method.
func (m *MockClient) SCP(destPath string, contents fs.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SCP", destPath, contents)
	ret0, _ := ret[0].(error)
	return ret0
}

// SCP indicates an expected call of SCP.
func (mr *MockClientMockRecorder) SCP(destPath, contents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SCP", reflect.TypeOf((*MockClient)(nil).SCP), destPath, contents)
}
